// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseService.Models;

#nullable disable

namespace PurchaseService.Migrations
{
    [DbContext(typeof(PurchaseDBContext))]
    partial class PurchaseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurchaseService.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityPurchased")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = 1,
                            EmailId = "Franken@gmail.com",
                            ProductId = "P101",
                            QuantityPurchased = 2,
                            TotalPrice = 9000m
                        },
                        new
                        {
                            PurchaseId = 2,
                            EmailId = "Franken@gmail.com",
                            ProductId = "P143",
                            QuantityPurchased = 1,
                            TotalPrice = 1114.52m
                        },
                        new
                        {
                            PurchaseId = 3,
                            EmailId = "SamRock@gmail.com",
                            ProductId = "P120",
                            QuantityPurchased = 4,
                            TotalPrice = 2085m
                        },
                        new
                        {
                            PurchaseId = 4,
                            EmailId = "PaulGrey@gmail.com",
                            ProductId = "P148",
                            QuantityPurchased = 1,
                            TotalPrice = 2561.51m
                        },
                        new
                        {
                            PurchaseId = 5,
                            EmailId = "PaulGrey@gmail.com",
                            ProductId = "P101",
                            QuantityPurchased = 10,
                            TotalPrice = 1265m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
