// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Models;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "P101",
                            CategoryId = (byte)1,
                            Price = 18000000m,
                            ProductName = "Lamborghini Gallardo Spyder",
                            QuantityAvailable = 10
                        },
                        new
                        {
                            ProductId = "P102",
                            CategoryId = (byte)1,
                            Price = 7000000m,
                            ProductName = "Harley Davidson Iron 883",
                            QuantityAvailable = 10
                        },
                        new
                        {
                            ProductId = "P103",
                            CategoryId = (byte)2,
                            Price = 2056m,
                            ProductName = "Oil painting on Canvas",
                            QuantityAvailable = 200
                        },
                        new
                        {
                            ProductId = "P104",
                            CategoryId = (byte)2,
                            Price = 9000m,
                            ProductName = "Marble Elephants Statue",
                            QuantityAvailable = 100
                        },
                        new
                        {
                            ProductId = "P105",
                            CategoryId = (byte)3,
                            Price = 15000m,
                            ProductName = "Dining Table",
                            QuantityAvailable = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
